# Generated by Django 4.2.4 on 2023-09-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0003_polystyrene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polystyrene',
            old_name='name_polystyrene',
            new_name='name_layer',
        ),
    ]
