# Generated by Django 4.2.4 on 2023-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0004_rename_name_polystyrene_polystyrene_name_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalIsolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_layer', models.CharField(max_length=100)),
                ('thickness', models.FloatField()),
                ('thermal_conductivity', models.FloatField()),
                ('cost', models.FloatField()),
                ('package_square_meters', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Polystyrene',
        ),
    ]
