# Generated by Django 4.2.4 on 2023-09-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0006_remove_material_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThermalIsolation',
        ),
    ]
