# Generated by Django 4.2.4 on 2023-09-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0007_delete_thermalisolation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
