# Generated by Django 4.2.4 on 2023-09-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0008_delete_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeLayer',
        ),
    ]
