# Generated by Django 4.2.4 on 2023-09-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heat', '0009_delete_typelayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_layer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_layer', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalIsolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('thermal_conductivity', models.FloatField()),
                ('cost', models.FloatField()),
                ('package_square_meters', models.FloatField()),
                ('name_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='type_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.typelayer'),
        ),
    ]
