# Generated by Django 4.2.4 on 2023-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0014_plaster_isolation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name_layer',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
